name: Python application

on:
  push:
    branches: [ main, packaging ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.1"
    - name: Install dependencies
      run: |
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
        
    - name: Test with unittest
      run: |
        poetry run python -m unittest tests/test_normalize.py
Â© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
